var easeIn = Power1.easeIn;
var easeOut = Power1.easeOut;
var timeline = new TimelineLite({onComplete: onComplete});
        timeline.add('frame1')
            .addDelay(0.5, 'frame1-copyfade')
            .to('.copy1', 1, {opacity: 1}).add('frame1-copyfade')
            .addDelay(2, 'frame1-copyfadeout')
            .to('.copy1', 1, {opacity: 0}).add('frame1-copyfadeout')
        timeline.add('frame2')
            .to('.background1', 1, {opacity: 0}, 'frame2')
            .to('.background2', 1, {opacity: 1}, 'frame2')
            .addDelay(0.5, 'frame2-copy')
            .to('.copy2', 1, {opacity: 1}, 'frame2-copy')
            .to('.copy3', 1, {opacity: 1})
            .addDelay(2, 'frame2-copyfadeout')
            .to('.copy2,.copy3', 1, {opacity: 0}).add('frame2-copyfadeout')
        timeline.add('frame3')
            .to('.copy4', 1, {opacity: 1}, 'frame3-copy')
            .addDelay(0.5, 'frame3-cta')
            .to('.cta', 1, {opacity: 1}).add('frame3-cta')
        timeline.add('frame4')