var timeline = new TimelineLite();
	timeline.add('frame1')
		.to('.spring', 0.3, { height: '-=10', top: '+=5' })
		.to('.spring', 0.3, { height: '+=10', top: '-=5' })
		.to('.spring', 0.3, { height: '-=15', top: '+=7' })
		.to('.spring', 0.3, { height: '+=15', top: '-=7' })
		.to('.spring', 0.3, { height: '-=10', top: '+=5' })
		.to('.spring', 0.3, { height: '+=10', top: '-=5' })
		.to('.spring', 0.3, { height: '-=15', top: '+=7' })
		.to('.spring', 0.3, { height: '+=15', top: '-=7' })
	timeline.add('frame2')
		.to('.wipe', 0.5, { width: 255 })
		.to('.wipe-line', 0.5, { left: 255 }, '-=0.5')
		.to('.wipe-line', 0.3, { left: 265 })
		.to('.background1, .spring', 0, { opacity: 0 })
		.addDelay(3, 'frame3')
	timeline.add('frame3')
		.to('.wipe', 1, { opacity: 0 }).add('frame3-logo')
		.to('.background3', 1, { opacity: 1 }).add('frame3-background')
		.addDelay(0.5, 'cta')
		.to('.cta', 1, { opacity: 1 }).add('cta')
	timeline.add('frame4')