var easeIn = Power1.easeIn;
var easeOut = Power1.easeOut;
var timeline = new TimelineLite({onComplete: onComplete});
        timeline.add('frame1').add('start')
            .to('.masks .top', 0.5, {top:"-=35", ease:easeOut})
            .to('.masks .bottom-right', 0.5, {height:56, ease:easeOut}, 'start').add('frame1-mask')
            .to('.masks .bottom-bottom', 0.5, {height:36, ease:easeOut}, 'frame1-mask')
            .to('.masks .left', 0.5, {top:"-=56", height:56, ease:easeOut}, 'frame1-mask')
            .addDelay(0.5, 'frame2')
        timeline.add('frame2')
            .to('.copy1', 2, {opacity:1, ease:easeOut})
            .addDelay(2, 'frame3')
        timeline.add('frame3')
            .to('.backgrounds,.copy1', 1, {opacity:0, ease:easeOut})
            .to('.copy2', 1.5, {opacity:1, ease:easeOut})
            .addDelay(1, 'frame4')
        timeline.add('frame4')
            .to('.logo', 1.5, {opacity:1, ease:easeOut})
            .to('.cta', 1.5, {opacity:1, ease:easeOut})
        timeline.add('end')