var easeIn = Power1.easeIn;
var easeOut = Power1.easeOut;
var timeline = new TimelineLite({onComplete: onComplete});
        timeline.add('frame1').add('start')
        .to('.copy1', 1, {opacity:1, ease:easeIn})
        .addDelay(2)
        .to('.copy1', 1, {opacity:0, ease:easeOut})
        timeline.add('frame2')
        .to('.copy2', 1, {opacity:1, ease:easeIn})
        .to('.dish', 2, {opacity:1, ease:easeIn})
            .addDelay(1.5, 'frame3')
        timeline.add('frame3')
            .to('.copy2', 1, {opacity:0, ease:easeOut}, 'frame3')
            .to('.copy3,.legal', 1, {opacity:1, ease:easeIn})
            .addDelay(2)
            .to('.copy3,.legal', 1, {opacity:0, ease:easeOut})
            .to('.background2', 1, {opacity:1, ease:easeIn})
            .to('.copy4', 1, {opacity:1, ease:easeIn})
            .to('.badge', 1, {opacity:1, ease:easeIn})
            .to('.logo', .25, {top:'13px', ease:easeIn})
            .to('.cta', 2, {opacity:1, ease:easeOut})
        timeline.add('frame4').add('end')